services:
  indoaddr-app:
    build: .
    container_name: indoaddr_app
    ports:
      - "8000:8000"
    volumes:
      # mount model dari host ke container
      - /home/fajar/IndoAddr-NER/models:/app/models
    restart: unless-stopped
